# Generated by Django 4.2.24 on 2025-11-06 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMentorRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_relationships', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_relationship_as_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Связь пользователь-ментор',
                'verbose_name_plural': 'Связи пользователь-ментор',
                'db_table': 'user_mentor_relationships',
            },
        ),
    ]
