# Generated by Django 4.2.24 on 2025-11-06 14:18

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usermentorrelationship'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='balance_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Баланс'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='balance_currency',
            field=models.CharField(choices=[('RUB', 'Рубли'), ('USD', 'Доллары'), ('EUR', 'Евро')], default='RUB', max_length=3, verbose_name='Валюта баланса'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='balance_updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Баланс обновлен'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('transaction_type', models.CharField(choices=[('income', 'Пополнение'), ('outcome', 'Вывод'), ('bonus', 'Бонус'), ('Pay', 'Выплата'), ('transfer', 'Перевод')], max_length=10)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'В обработке'), ('completed', 'Завершено'), ('failed', 'Ошибка')], default='completed', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'db_table': 'user_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
