# Generated by Django 4.2.7 on 2025-11-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='telegram_link',
            field=models.URLField(blank=True, null=True, verbose_name='Telegram ссылка'),
        ),
    ]
